New upstream source

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -519,7 +519,7 @@ fi
 
 
 VERSION="0"
-SUBVERSION="10"
+SUBVERSION="11"
 
 
 
@@ -1023,84 +1023,81 @@ fi
 		
 
 
-DOTLOCK="no"
 # Extract the first word of "mutt.dotlock", so it can be a program name with args.
 set dummy mutt.dotlock; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1031: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_DOTLOCKDOT'+set}'`\" = set"; then
+echo "configure:1030: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_DOTLOCK_OLD'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$DOTLOCKDOT" in
+  case "$DOTLOCK_OLD" in
   /*)
-  ac_cv_path_DOTLOCKDOT="$DOTLOCKDOT" # Let the user override the test with a path.
+  ac_cv_path_DOTLOCK_OLD="$DOTLOCK_OLD" # Let the user override the test with a path.
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
   for ac_dir in `echo $PATH | sed "s/:/ /g"` $ac_dummy; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_DOTLOCKDOT="$ac_dir/$ac_word"
+      ac_cv_path_DOTLOCK_OLD="$ac_dir/$ac_word"
       break
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_path_DOTLOCKDOT" && ac_cv_path_DOTLOCKDOT="no"
+  test -z "$ac_cv_path_DOTLOCK_OLD" && ac_cv_path_DOTLOCK_OLD="no"
   ;;
 esac
 fi
-DOTLOCKDOT="$ac_cv_path_DOTLOCKDOT"
-if test -n "$DOTLOCKDOT"; then
-  echo "$ac_t""$DOTLOCKDOT" 1>&6
+DOTLOCK_OLD="$ac_cv_path_DOTLOCK_OLD"
+if test -n "$DOTLOCK_OLD"; then
+  echo "$ac_t""$DOTLOCK_OLD" 1>&6
 else
   echo "$ac_t""no" 1>&6
 fi
 
-if ! test "x$ac_cv_path_DOTLOCKDOT" = "xno" ; then
-	DOTLOCK="$ac_cv_path_DOTLOCKDOT"
-fi
-
-# Extract the first word of "mutt_dotlock", so it can be a program name with args.
+if test x$ac_cv_path_DOTLOCK_OLD = xno ; then
+	# Extract the first word of "mutt_dotlock", so it can be a program name with args.
 set dummy mutt_dotlock; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1067: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_DOTLOCKUSCORE'+set}'`\" = set"; then
+echo "configure:1063: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_DOTLOCK'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  case "$DOTLOCKUSCORE" in
+  case "$DOTLOCK" in
   /*)
-  ac_cv_path_DOTLOCKUSCORE="$DOTLOCKUSCORE" # Let the user override the test with a path.
+  ac_cv_path_DOTLOCK="$DOTLOCK" # Let the user override the test with a path.
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
-  for ac_dir in `echo $PATH | sed "s/:/ /g"` $ac_dummy; do
+  for ac_dir in `echo $PATH | sed "s/:/ /g"`$ac_dummy; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_path_DOTLOCKUSCORE="$ac_dir/$ac_word"
+      ac_cv_path_DOTLOCK="$ac_dir/$ac_word"
       break
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_path_DOTLOCKUSCORE" && ac_cv_path_DOTLOCKUSCORE="no"
+  test -z "$ac_cv_path_DOTLOCK" && ac_cv_path_DOTLOCK="no"
   ;;
 esac
 fi
-DOTLOCKUSCORE="$ac_cv_path_DOTLOCKUSCORE"
-if test -n "$DOTLOCKUSCORE"; then
-  echo "$ac_t""$DOTLOCKUSCORE" 1>&6
+DOTLOCK="$ac_cv_path_DOTLOCK"
+if test -n "$DOTLOCK"; then
+  echo "$ac_t""$DOTLOCK" 1>&6
 else
   echo "$ac_t""no" 1>&6
 fi
 
-if ! test "x$ac_cv_path_DOTLOCKUSCORE" = "xno" ; then
-	DOTLOCK="$ac_cv_path_DOTLOCKUSCORE"
+else
+	ac_cv_path_DOTLOCK=$ac_cv_path_DOTLOCK_OLD
 fi
 
-if test "x$DOTLOCK" = "xno" ; then
-	echo "ERROR: mutt.dotlock or mutt_dotlock is required to build this package." >&2
+if test x$ac_cv_path_DOTLOCK = xno ; then
+	echo "ERROR: mutt_dotlock is required to build this package." >&2
 	echo "ERROR: You can get it from the mutt package's source code." >&2
 	exit 1
 fi
+
 
 cat >> confdefs.h <<EOF
 #define DOTLOCK "$ac_cv_path_DOTLOCK"
@@ -1117,7 +1114,7 @@ MODULES="m_inmail"
 # Extract the first word of "finger", so it can be a program name with args.
 set dummy finger; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1121: checking for $ac_word" >&5
+echo "configure:1118: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_FINGER'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1314,8 +1311,7 @@ s%@MAWK@%$MAWK%g
 s%@GAWK@%$GAWK%g
 s%@NAWK@%$NAWK%g
 s%@AWK@%$AWK%g
-s%@DOTLOCKDOT@%$DOTLOCKDOT%g
-s%@DOTLOCKUSCORE@%$DOTLOCKUSCORE%g
+s%@DOTLOCK_OLD@%$DOTLOCK_OLD%g
 s%@DOTLOCK@%$DOTLOCK%g
 s%@path_fetchaddr@%$path_fetchaddr%g
 s%@FINGER@%$FINGER%g
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl -*-sh-mode-*-
 
 AC_INIT(fetchaddr.c)
 VERSION="0"
-SUBVERSION="10"
+SUBVERSION="11"
 
 AC_SUBST(VERSION)
 AC_SUBST(SUBVERSION)
@@ -74,22 +74,19 @@ fi
 		
 AC_SUBST(AWK)
 
-DOTLOCK="no"
-AC_PATH_PROG(DOTLOCKDOT, mutt.dotlock, no, `echo $PATH | sed "s/:/ /g"` )
-if ! test "x$ac_cv_path_DOTLOCKDOT" = "xno" ; then
-	DOTLOCK="$ac_cv_path_DOTLOCKDOT"
+AC_PATH_PROG(DOTLOCK_OLD, mutt.dotlock, no, `echo $PATH | sed "s/:/ /g"` )
+if test x$ac_cv_path_DOTLOCK_OLD = xno ; then
+	AC_PATH_PROG(DOTLOCK, mutt_dotlock, no, `echo $PATH | sed "s/:/ /g"`)
+else
+	ac_cv_path_DOTLOCK=$ac_cv_path_DOTLOCK_OLD
 fi
 
-AC_PATH_PROG(DOTLOCKUSCORE, mutt_dotlock, no, `echo $PATH | sed "s/:/ /g"` )
-if ! test "x$ac_cv_path_DOTLOCKUSCORE" = "xno" ; then
-	DOTLOCK="$ac_cv_path_DOTLOCKUSCORE"
-fi
-
-if test "x$DOTLOCK" = "xno" ; then
-	echo "ERROR: mutt.dotlock or mutt_dotlock is required to build this package." >&2
+if test x$ac_cv_path_DOTLOCK = xno ; then
+	echo "ERROR: mutt_dotlock is required to build this package." >&2
 	echo "ERROR: You can get it from the mutt package's source code." >&2
 	exit 1
 fi
+
 
 AC_DEFINE_UNQUOTED(DOTLOCK, "$ac_cv_path_DOTLOCK")
 AC_SUBST(DOTLOCK)
