rebuild from configure.in with vcf support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CPP EGREP BASH KSH BINSH SH AWK MAWK GAWK NAWK TAC TACTARGET DOTLOCK_OLD DOTLOCK DOTLOCK_TARGET DOTLOCKBASE path_fetchaddr FINGER ABOOK ADDR_EMAIL YPCAT NISCAT GETENT GPG PGPK PGP EVOLUTION_ADDRESSBOOK_EXPORT PERL XCODEBUILD PBXBUILD LBDB_VERSION MODULES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CPP EGREP BASH KSH BINSH SH AWK MAWK GAWK NAWK TAC TACTARGET DOTLOCK_OLD DOTLOCK DOTLOCK_TARGET DOTLOCKBASE path_fetchaddr FINGER ABOOK ADDR_EMAIL YPCAT NISCAT GETENT GPG PGPK PGP EVOLUTION_ADDRESSBOOK_EXPORT PERL XCODEBUILD PBXBUILD VFORMAT LBDB_VERSION MODULES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4695,6 +4695,221 @@ fi
 	fi
 fi
 
+VFORMAT="no"
+if test "${ac_cv_header_vf_iface_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for vf_iface.h" >&5
+echo $ECHO_N "checking for vf_iface.h... $ECHO_C" >&6
+if test "${ac_cv_header_vf_iface_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_vf_iface_h" >&5
+echo "${ECHO_T}$ac_cv_header_vf_iface_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking vf_iface.h usability" >&5
+echo $ECHO_N "checking vf_iface.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <vf_iface.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking vf_iface.h presence" >&5
+echo $ECHO_N "checking vf_iface.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <vf_iface.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: vf_iface.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: vf_iface.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: vf_iface.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: vf_iface.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: vf_iface.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: vf_iface.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: vf_iface.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: vf_iface.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: vf_iface.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for vf_iface.h" >&5
+echo $ECHO_N "checking for vf_iface.h... $ECHO_C" >&6
+if test "${ac_cv_header_vf_iface_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_vf_iface_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_vf_iface_h" >&5
+echo "${ECHO_T}$ac_cv_header_vf_iface_h" >&6
+
+fi
+if test $ac_cv_header_vf_iface_h = yes; then
+
+  echo "$as_me:$LINENO: checking for vf_read_file in -lvformat" >&5
+echo $ECHO_N "checking for vf_read_file in -lvformat... $ECHO_C" >&6
+if test "${ac_cv_lib_vformat_vf_read_file+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lvformat  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char vf_read_file ();
+int
+main ()
+{
+vf_read_file ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_vformat_vf_read_file=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_vformat_vf_read_file=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_vformat_vf_read_file" >&5
+echo "${ECHO_T}$ac_cv_lib_vformat_vf_read_file" >&6
+if test $ac_cv_lib_vformat_vf_read_file = yes; then
+
+    MODULES="$MODULES m_vcf"
+    VFORMAT="yes"
+
+fi
+
+
+fi
+
+
+
+
 MODULES_SH=""
 for i in $MODULES ; do
 	MODULES_SH="$MODULES_SH $i.sh"
@@ -5393,6 +5608,7 @@ s,@EVOLUTION_ADDRESSBOOK_EXPORT@,$EVOLUTION_ADDRESSBOOK_EXPORT,;t t
 s,@PERL@,$PERL,;t t
 s,@XCODEBUILD@,$XCODEBUILD,;t t
 s,@PBXBUILD@,$PBXBUILD,;t t
+s,@VFORMAT@,$VFORMAT,;t t
 s,@LBDB_VERSION@,$LBDB_VERSION,;t t
 s,@MODULES@,$MODULES,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
