* Create ~/.lbdb/m_inmail.list in lbdb-fetchaddr if it does not exist.   * Fix manpage lbdb-fetchaddr(1) to refer to the correct db filename.

diff --git a/lbdb-fetchaddr.sh.in b/lbdb-fetchaddr.sh.in
--- a/lbdb-fetchaddr.sh.in
+++ b/lbdb-fetchaddr.sh.in
@@ -27,6 +27,14 @@ exec_prefix=@exec_prefix@
 fetchaddr=@libdir@/fetchaddr
 db=$HOME/.lbdb/m_inmail.list
 
+if [ ! -f $db ]; then
+  touch $db
+  if [ ! -f $db ]; then
+    echo "Can't create $db" >&2
+    exit 1
+  fi
+fi
+
 if ! $dotlock -r 10 -f $db ; then
   echo "Can't lock $db [dotlock returned $rv]." >&2
   exit 1
