Replace undefined $rv by $?.

diff --git a/lbdb-munge.sh.in b/lbdb-munge.sh.in
--- a/lbdb-munge.sh.in
+++ b/lbdb-munge.sh.in
@@ -56,7 +56,7 @@ if $dotlock -r 10 -f $db
 then
     : # okay, do nothing
 else
-    echo "Can't lock $db [dotlock returned $rv]." >&2
+    echo "Can't lock $db [dotlock returned $?]." >&2
     exit 1
 fi
 
