m_mu: Add configuration option MU_IGNORE_MISSINGNAME
to suppress showing addesses without name (reverts to old behavior).

diff --git a/tests/testsuite b/tests/testsuite
--- a/tests/testsuite
+++ b/tests/testsuite
@@ -624,8 +624,9 @@ at_help_all="1;m_muttalias.at:19;m_muttalias;;
 12;m_vcf.at:43;m_vcf no realname;;
 13;m_vcf.at:51;m_vcf crlf lineending;;
 14;m_mu.at:19;m_mu;;
-15;m_mu.at:34;m_mu personal;;
-16;m_mu.at:59;m_mu after;;
+15;m_mu.at:35;m_mu personal;;
+16;m_mu.at:61;m_mu after;;
+17;m_mu.at:87;m_mu ignore missingname;;
 "
 # List of the all the test groups.
 at_groups_all=`printf "%s\n" "$at_help_all" | sed 's/;.*//'`
@@ -639,7 +640,7 @@ at_fn_validate_ranges ()
   for at_grp
   do
     eval at_value=\$$at_grp
-    if test $at_value -lt 1 || test $at_value -gt 16; then
+    if test $at_value -lt 1 || test $at_value -gt 17; then
       printf "%s\n" "invalid test group: $at_value" >&2
       exit 1
     fi
@@ -2884,12 +2885,14 @@ printf "%s\n" "$at_srcdir/m_mu.at:26: env LBDB_OVERRIDE_METHODS=m_mu \\
               OVERRIDE_MU_HOME=muhome \\
               OVERRIDE_MU_PERSONAL='' \\
               OVERRIDE_MU_AFTER='' \\
+              OVERRIDE_MU_IGNORE_MISSINGNAME='' \\
           lbdbq example"
 at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:26"
 ( $at_check_trace; env LBDB_OVERRIDE_METHODS=m_mu \
               OVERRIDE_MU_HOME=muhome \
               OVERRIDE_MU_PERSONAL='' \
               OVERRIDE_MU_AFTER='' \
+              OVERRIDE_MU_IGNORE_MISSINGNAME='' \
           lbdbq example
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
@@ -2906,16 +2909,16 @@ $at_traceon; }
 read at_status <"$at_status_file"
 #AT_STOP_14
 #AT_START_15
-at_fn_group_banner 15 'm_mu.at:34' \
+at_fn_group_banner 15 'm_mu.at:35' \
   "m_mu personal" "                                  " 5
 at_xfail=no
 (
   printf "%s\n" "15. $at_setup_line: testing $at_desc ..."
   $at_traceon
 
-printf "%s\n" "m_mu.at:35" >"$at_check_line_file"
+printf "%s\n" "m_mu.at:36" >"$at_check_line_file"
 (! which mu) \
-  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:35"
+  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:36"
 # mu before 1.8 has broken --personal switch, so skip this test
 muversion=`mu --version | head -n 1 \
            | sed -n 's/.* \([0-9]\+\.[0-9]\+\).*/\1/p'`
@@ -2924,29 +2927,14 @@ case "$muversion" in
      1.[0-7]) muversionstate=0;;
      2-9.*) muversionstate=0;;
 esac
-printf "%s\n" "m_mu.at:44" >"$at_check_line_file"
+printf "%s\n" "m_mu.at:45" >"$at_check_line_file"
 (exit $muversionstate) \
-  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:44"
+  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:45"
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:46: perl \$abs_srcdir/gen-maildir \$abs_srcdir/data"
-at_fn_check_prepare_dynamic "perl $abs_srcdir/gen-maildir $abs_srcdir/data" "m_mu.at:46"
+printf "%s\n" "$at_srcdir/m_mu.at:47: perl \$abs_srcdir/gen-maildir \$abs_srcdir/data"
+at_fn_check_prepare_dynamic "perl $abs_srcdir/gen-maildir $abs_srcdir/data" "m_mu.at:47"
 ( $at_check_trace; perl $abs_srcdir/gen-maildir $abs_srcdir/data
-) >>"$at_stdout" 2>>"$at_stderr" 5>&-
-at_status=$? at_failed=false
-$at_check_filter
-at_fn_diff_devnull "$at_stderr" || at_failed=:
-at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:46"
-$at_failed && at_fn_log_failure
-$at_traceon; }
-
-{ set +x
-printf "%s\n" "$at_srcdir/m_mu.at:47: mu init --maildir=maildir --muhome=muhome \\
-                  --my-address=me@example.org >/dev/null"
-at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:47"
-( $at_check_trace; mu init --maildir=maildir --muhome=muhome \
-                  --my-address=me@example.org >/dev/null
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
@@ -2957,22 +2945,24 @@ $at_failed && at_fn_log_failure
 $at_traceon; }
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:49: mu index --muhome=muhome >/dev/null"
-at_fn_check_prepare_trace "m_mu.at:49"
-( $at_check_trace; mu index --muhome=muhome >/dev/null
+printf "%s\n" "$at_srcdir/m_mu.at:48: mu init --maildir=maildir --muhome=muhome \\
+                  --my-address=me@example.org >/dev/null"
+at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:48"
+( $at_check_trace; mu init --maildir=maildir --muhome=muhome \
+                  --my-address=me@example.org >/dev/null
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:49"
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:48"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:50: cat \$abs_srcdir/data/m_mu-personal.expected > expout"
-at_fn_check_prepare_dynamic "cat $abs_srcdir/data/m_mu-personal.expected > expout" "m_mu.at:50"
-( $at_check_trace; cat $abs_srcdir/data/m_mu-personal.expected > expout
+printf "%s\n" "$at_srcdir/m_mu.at:50: mu index --muhome=muhome >/dev/null"
+at_fn_check_prepare_trace "m_mu.at:50"
+( $at_check_trace; mu index --muhome=muhome >/dev/null
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
@@ -2983,23 +2973,38 @@ $at_failed && at_fn_log_failure
 $at_traceon; }
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:51: env LBDB_OVERRIDE_METHODS=m_mu \\
+printf "%s\n" "$at_srcdir/m_mu.at:51: cat \$abs_srcdir/data/m_mu-personal.expected > expout"
+at_fn_check_prepare_dynamic "cat $abs_srcdir/data/m_mu-personal.expected > expout" "m_mu.at:51"
+( $at_check_trace; cat $abs_srcdir/data/m_mu-personal.expected > expout
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:51"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:52: env LBDB_OVERRIDE_METHODS=m_mu \\
               OVERRIDE_MU_HOME=muhome \\
               OVERRIDE_MU_PERSONAL=true \\
               OVERRIDE_MU_AFTER='' \\
+              OVERRIDE_MU_IGNORE_MISSINGNAME='' \\
           lbdbq example"
-at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:51"
+at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:52"
 ( $at_check_trace; env LBDB_OVERRIDE_METHODS=m_mu \
               OVERRIDE_MU_HOME=muhome \
               OVERRIDE_MU_PERSONAL=true \
               OVERRIDE_MU_AFTER='' \
+              OVERRIDE_MU_IGNORE_MISSINGNAME='' \
           lbdbq example
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 $at_diff expout "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:51"
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:52"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
@@ -3009,16 +3014,16 @@ $at_traceon; }
 read at_status <"$at_status_file"
 #AT_STOP_15
 #AT_START_16
-at_fn_group_banner 16 'm_mu.at:59' \
+at_fn_group_banner 16 'm_mu.at:61' \
   "m_mu after" "                                     " 5
 at_xfail=no
 (
   printf "%s\n" "16. $at_setup_line: testing $at_desc ..."
   $at_traceon
 
-printf "%s\n" "m_mu.at:60" >"$at_check_line_file"
+printf "%s\n" "m_mu.at:62" >"$at_check_line_file"
 (! which mu) \
-  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:60"
+  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:62"
 # mu before 1.8 seems to have broken --after switch, so skip this test
 muversion=`mu --version | head -n 1 \
            | sed -n 's/.* \([0-9]\+\.[0-9]\+\).*/\1/p'`
@@ -3027,42 +3032,29 @@ case "$muversion" in
      1.[0-7]) muversionstate=0;;
      2-9.*) muversionstate=0;;
 esac
-printf "%s\n" "m_mu.at:69" >"$at_check_line_file"
+printf "%s\n" "m_mu.at:71" >"$at_check_line_file"
 (exit $muversionstate) \
-  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:69"
+  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:71"
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:71: perl \$abs_srcdir/gen-maildir \$abs_srcdir/data"
-at_fn_check_prepare_dynamic "perl $abs_srcdir/gen-maildir $abs_srcdir/data" "m_mu.at:71"
+printf "%s\n" "$at_srcdir/m_mu.at:73: perl \$abs_srcdir/gen-maildir \$abs_srcdir/data"
+at_fn_check_prepare_dynamic "perl $abs_srcdir/gen-maildir $abs_srcdir/data" "m_mu.at:73"
 ( $at_check_trace; perl $abs_srcdir/gen-maildir $abs_srcdir/data
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:71"
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:73"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:72: mu init --maildir=maildir --muhome=muhome \\
+printf "%s\n" "$at_srcdir/m_mu.at:74: mu init --maildir=maildir --muhome=muhome \\
                   --my-address=me@example.org >/dev/null"
-at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:72"
+at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:74"
 ( $at_check_trace; mu init --maildir=maildir --muhome=muhome \
                   --my-address=me@example.org >/dev/null
-) >>"$at_stdout" 2>>"$at_stderr" 5>&-
-at_status=$? at_failed=false
-$at_check_filter
-at_fn_diff_devnull "$at_stderr" || at_failed=:
-at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:72"
-$at_failed && at_fn_log_failure
-$at_traceon; }
-
-{ set +x
-printf "%s\n" "$at_srcdir/m_mu.at:74: mu index --muhome=muhome >/dev/null"
-at_fn_check_prepare_trace "m_mu.at:74"
-( $at_check_trace; mu index --muhome=muhome >/dev/null
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
@@ -3073,36 +3065,51 @@ $at_failed && at_fn_log_failure
 $at_traceon; }
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:75: cat \$abs_srcdir/data/m_mu-after.expected > expout"
-at_fn_check_prepare_dynamic "cat $abs_srcdir/data/m_mu-after.expected > expout" "m_mu.at:75"
+printf "%s\n" "$at_srcdir/m_mu.at:76: mu index --muhome=muhome >/dev/null"
+at_fn_check_prepare_trace "m_mu.at:76"
+( $at_check_trace; mu index --muhome=muhome >/dev/null
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:76"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:77: cat \$abs_srcdir/data/m_mu-after.expected > expout"
+at_fn_check_prepare_dynamic "cat $abs_srcdir/data/m_mu-after.expected > expout" "m_mu.at:77"
 ( $at_check_trace; cat $abs_srcdir/data/m_mu-after.expected > expout
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:75"
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:77"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
 { set +x
-printf "%s\n" "$at_srcdir/m_mu.at:76: env LBDB_OVERRIDE_METHODS=m_mu \\
+printf "%s\n" "$at_srcdir/m_mu.at:78: env LBDB_OVERRIDE_METHODS=m_mu \\
               OVERRIDE_MU_HOME=muhome \\
               OVERRIDE_MU_PERSONAL='' \\
               OVERRIDE_MU_AFTER='1684195200' \\
+              OVERRIDE_MU_IGNORE_MISSINGNAME='' \\
           lbdbq example"
-at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:76"
+at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:78"
 ( $at_check_trace; env LBDB_OVERRIDE_METHODS=m_mu \
               OVERRIDE_MU_HOME=muhome \
               OVERRIDE_MU_PERSONAL='' \
               OVERRIDE_MU_AFTER='1684195200' \
+              OVERRIDE_MU_IGNORE_MISSINGNAME='' \
           lbdbq example
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 $at_diff expout "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:76"
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:78"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
@@ -3111,3 +3118,96 @@ $at_traceon; }
 ) 5>&1 2>&1 7>&- | eval $at_tee_pipe
 read at_status <"$at_status_file"
 #AT_STOP_16
+#AT_START_17
+at_fn_group_banner 17 'm_mu.at:87' \
+  "m_mu ignore missingname" "                        " 5
+at_xfail=no
+(
+  printf "%s\n" "17. $at_setup_line: testing $at_desc ..."
+  $at_traceon
+
+printf "%s\n" "m_mu.at:88" >"$at_check_line_file"
+(! which mu) \
+  && at_fn_check_skip 77 "$at_srcdir/m_mu.at:88"
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:89: perl \$abs_srcdir/gen-maildir \$abs_srcdir/data"
+at_fn_check_prepare_dynamic "perl $abs_srcdir/gen-maildir $abs_srcdir/data" "m_mu.at:89"
+( $at_check_trace; perl $abs_srcdir/gen-maildir $abs_srcdir/data
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:89"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:90: mu init --maildir=maildir --muhome=muhome \\
+                  --my-address=me@example.org >/dev/null"
+at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:90"
+( $at_check_trace; mu init --maildir=maildir --muhome=muhome \
+                  --my-address=me@example.org >/dev/null
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:90"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:92: mu index --muhome=muhome >/dev/null"
+at_fn_check_prepare_trace "m_mu.at:92"
+( $at_check_trace; mu index --muhome=muhome >/dev/null
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:92"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:93: cat \$abs_srcdir/data/m_mu-ignoremissingname.expected > expout"
+at_fn_check_prepare_dynamic "cat $abs_srcdir/data/m_mu-ignoremissingname.expected > expout" "m_mu.at:93"
+( $at_check_trace; cat $abs_srcdir/data/m_mu-ignoremissingname.expected > expout
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:93"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+{ set +x
+printf "%s\n" "$at_srcdir/m_mu.at:94: env LBDB_OVERRIDE_METHODS=m_mu \\
+              OVERRIDE_MU_HOME=muhome \\
+              OVERRIDE_MU_PERSONAL='' \\
+              OVERRIDE_MU_AFTER='' \\
+              OVERRIDE_MU_IGNORE_MISSINGNAME='true' \\
+          lbdbq example"
+at_fn_check_prepare_notrace 'an embedded newline' "m_mu.at:94"
+( $at_check_trace; env LBDB_OVERRIDE_METHODS=m_mu \
+              OVERRIDE_MU_HOME=muhome \
+              OVERRIDE_MU_PERSONAL='' \
+              OVERRIDE_MU_AFTER='' \
+              OVERRIDE_MU_IGNORE_MISSINGNAME='true' \
+          lbdbq example
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+$at_diff expout "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/m_mu.at:94"
+$at_failed && at_fn_log_failure
+$at_traceon; }
+
+  set +x
+  $at_times_p && times >"$at_times_file"
+) 5>&1 2>&1 7>&- | eval $at_tee_pipe
+read at_status <"$at_status_file"
+#AT_STOP_17
